export const initialState = {
  isLogin: false,
  userInfo: null,
  accessToken: "",
  tags: [
    { name: "Blue", isColorTag: 1, id: 1 },
    { name: "Green", isColorTag: 1, id: 2 },
    { name: "Red", isColorTag: 1, id: 3 },
    { name: "Pink", isColorTag: 1, id: 4 },
    { name: "Black", isColorTag: 1, id: 5 },
    { name: "Yellow", isColorTag: 1, id: 6 },
    { name: "Grey", isColorTag: 1, id: 7 },
    { name: "Orange", isColorTag: 1, id: 8 },
    { name: "White", isColorTag: 1, id: 9 },
    { name: "Brown", isColorTag: 1, id: 10 },
    { name: "Purple", isColorTag: 1, id: 11 },
    { name: "Beige", isColorTag: 1, id: 12 },
    { name: "Navy", isColorTag: 1, id: 13 },
    { name: "Peach", isColorTag: 1, id: 14 },
    { name: "Teal", isColorTag: 1, id: 15 },
    { name: "Maroon", isColorTag: 1, id: 16 },
    { name: "Gold", isColorTag: 0, id: 17 },
    { name: "Pastel", isColorTag: 0, id: 18 },
    { name: "Dark", isColorTag: 0, id: 19 },
    { name: "Neon", isColorTag: 0, id: 20 },
    { name: "Skin", isColorTag: 0, id: 21 },
    { name: "Rainbow", isColorTag: 0, id: 22 },
    { name: "Retro", isColorTag: 0, id: 23 },
    { name: "Vintage", isColorTag: 0, id: 24 },
    { name: "Food", isColorTag: 0, id: 25 },
    { name: "Summer", isColorTag: 0, id: 26 },
    { name: "Light", isColorTag: 0, id: 27 },
    { name: "Cream", isColorTag: 0, id: 28 },
    { name: "Earth", isColorTag: 0, id: 29 },
    { name: "Coffee", isColorTag: 0, id: 30 },
    { name: "Nature", isColorTag: 0, id: 31 },
    { name: "Warm", isColorTag: 0, id: 32 },
    { name: "Spring", isColorTag: 0, id: 33 },
    { name: "Night", isColorTag: 0, id: 34 },
    { name: "Space", isColorTag: 0, id: 35 },
    { name: "Winter", isColorTag: 0, id: 36 },
    { name: "Sunset", isColorTag: 0, id: 37 },
    { name: "Christmas", isColorTag: 0, id: 38 },
    { name: "Kids", isColorTag: 0, id: 39 },
    { name: "Happy", isColorTag: 0, id: 40 },
    { name: "Cold", isColorTag: 0, id: 41 },
    { name: "Fall", isColorTag: 0, id: 42 },
    { name: "Wedding", isColorTag: 0, id: 43 },
    { name: "Halloween", isColorTag: 0, id: 44 },
  ],
  palettes: [],
  rankingPalettes: [],
  showLoginModal: false,
};
